vulnerabilities = [
    ("Windows Defender", "Check if Windows Defender is running.", "Enable real-time protection."),
    ("Windows Firewall", "Check if Windows Firewall is enabled.", "Enable it to protect against unauthorized access."),
    ("User Account Control (UAC)", "Check if User Account Control (UAC) is enabled.", "Enable it to prevent unauthorized changes."),
    ("Remote Desktop Protocol (RDP)", "Check if Remote Desktop Protocol (RDP) is enabled.", "Disable it if not necessary."),
    ("Secure Boot", "Check if Secure Boot is enabled.", "Enable it to ensure system integrity."),
    ("BitLocker Drive Encryption", "Check if BitLocker drive encryption is enabled.", "Encrypt drives to protect data at rest."),
    ("Windows Update", "Check if Windows Update is enabled.", "Keep your system up to date to patch security vulnerabilities."),
    ("Password Policy", "Check if password policy is enforced.", "Set strong password policies to prevent unauthorized access."),
    ("Antivirus Software", "Check if antivirus software is installed and up to date.", "Install and regularly update antivirus software."),
    ("Network Sharing", "Check if network sharing is enabled.", "Disable network sharing if not required to prevent unauthorized access."),
    ("Guest Account", "Check if the Guest account is enabled.", "Disable the Guest account to prevent unauthorized access."),
    ("AutoRun", "Check if AutoRun is enabled for external devices.", "Disable AutoRun to prevent execution of malicious code."),
    ("Remote Registry Service", "Check if Remote Registry Service is enabled.", "Disable the Remote Registry Service to prevent unauthorized access."),
    ("Windows Script Host", "Check if Windows Script Host is enabled.", "Disable Windows Script Host to prevent execution of malicious scripts."),
    ("Microsoft Office Macros", "Check if Microsoft Office macros are enabled.", "Disable macros in Microsoft Office applications to prevent execution of malicious code."),
    ("Remote Desktop Services", "Check if Remote Desktop Services is enabled.", "Disable Remote Desktop Services if not necessary."),
    ("Windows Management Instrumentation (WMI)", "Check if WMI is enabled.", "Disable WMI if not necessary."),
    ("Guest Network", "Check if the guest network is enabled.", "Disable the guest network to prevent unauthorized access."),
    ("Unused Services", "Check for unused services running on the system.", "Disable or remove unused services to reduce the attack surface."),
    ("Unpatched Software", "Check for unpatched software vulnerabilities.", "Regularly update software to patch security vulnerabilities."),
    ("Weak Encryption", "Check for weak encryption algorithms in use.", "Use strong encryption algorithms to protect sensitive data."),
    ("Weak Passwords", "Check for weak passwords in use.", "Enforce strong password policies to prevent unauthorized access."),
    ("Open Ports", "Check for open ports on the system.", "Close unnecessary ports to reduce the attack surface."),
    ("Outdated Protocols", "Check for outdated protocols in use.", "Disable outdated protocols to prevent security vulnerabilities."),
    ("Physical Security", "Check for physical security vulnerabilities.", "Secure physical access to prevent unauthorized access to hardware."),
]
